I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/test_case/test_case_setup.rpy", line 662, in script call
    call screen maddies_house_scene
  File "game/deduction_qs.rpy", line 388, in script call
    $ renpy.call_screen(current_scene)
  File "game/test_case/test_case_setup.rpy", line 662, in script call
    call screen maddies_house_scene
  File "game/test_case/test_case_maddie.rpy", line 265, in script call
    "It's just a question. An honest question. This one should be easy, just make it clear."
  File "game/deduction_qs.rpy", line 268, in script
    $ maddie_culprit_point += 1
  File "game/deduction_qs.rpy", line 268, in <module>
    $ maddie_culprit_point += 1
NameError: name 'maddie_culprit_point' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/test_case/test_case_setup.rpy", line 662, in script call
    call screen maddies_house_scene
  File "game/deduction_qs.rpy", line 388, in script call
    $ renpy.call_screen(current_scene)
  File "game/test_case/test_case_setup.rpy", line 662, in script call
    call screen maddies_house_scene
  File "game/test_case/test_case_maddie.rpy", line 265, in script call
    "It's just a question. An honest question. This one should be easy, just make it clear."
  File "game/deduction_qs.rpy", line 268, in script
    $ maddie_culprit_point += 1
  File "C:\Users\Quinn\Documents\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Quinn\Documents\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/deduction_qs.rpy", line 268, in <module>
    $ maddie_culprit_point += 1
NameError: name 'maddie_culprit_point' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
detective and fidget test 1.4
Sun Mar 31 15:40:38 2024
