I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/dialogue_demo.rpy", line 20, in script
    w "Alright. Let me know if you need anything else."
Exception: Sayer 'w' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/dialogue_demo.rpy", line 20, in script
    w "Alright. Let me know if you need anything else."
  File "C:\Users\Quinn\Documents\renpy-8.1.1-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Quinn\Documents\renpy-8.1.1-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'w' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
detective test 1.3
Sun Mar 10 14:59:03 2024
